---
  extends: concierge-auctions-react
  rules:
    no-underscore-dangle:
      - error
      - allowAfterThis: true
        allow:
          - _handleNestedListToggle
          - _disableDisplay
          - _DEPRECATION_NOTICE
          - __IS_SMOOTH_SCROLLING
          - __scroll__direction
          - __CA_DELAYED_MODAL
          - _wq
          - __dataID__
          - _fbq
          - _hsq
